#!/usr/bin/env python3

#displays in browser the location 

import webbrowser, sys, pyperclip
if len(sys.argv)>1:
    address = ' '.join(sys.argv[1:])
else:
    address = pyperclip.paste()

webbrowser.open('http://www.google.com/maps/place/' + address)